name: flutter_blockly_example
description: Demonstrates how to use the flutter_blockly plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blockly:
    path: ../
  path_provider: ^2.1.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/html/index.html
    - assets/html/style.css
    - assets/html/script.js