name: flutter_blockly
description: A Flutter Blockly visual programming editor. The Blockly library adds an editor to your app that represents coding concepts as interlocking blocks.
repository: https://github.com/mobile-blockly/flutter_blockly
homepage: https://github.com/mobile-blockly/flutter_blockly
issue_tracker: https://github.com/mobile-blockly/flutter_blockly/issues
version: 1.4.3

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blockly
      ios:
        default_package: flutter_blockly
      web:
        default_package: flutter_blockly

topics:
  - blockly
  - flutter-blockly
